---
ko:
  simple_form:
    glitch_only: 글리치
    hints:
      defaults:
        setting_default_content_type_html: 게시물을 작성할 때, 형식을 지정하지 않았다면, HTML 형식으로 게시됩니다.
        setting_default_content_type_markdown: 게시물을 작성할 때, 형식을 지정하지 않았다면, 마크다운 형식으로 게시됩니다.
        setting_default_content_type_plain: 게시물을 작성할 때, 형식을 지정하지 않았다면, 일반 텍스트 형식으로 게시됩니다.
        setting_default_language: 작성하는 게시물의 언어가 자동적으로 설정됩니다. 항상 정확한 언어로 설정되지는 않습니다.
        setting_show_followers_count: 프로필에서 팔로워 수를 가립니다. 팔로워 수를 가리면 본인도 확인할 수 없으며, 일부 클라이언트에서는 팔로워 수가 음수로 표시됩니다.
        setting_skin: 선택한 마스토돈 테마의 스타일을 지정합니다.
    labels:
      defaults:
        setting_default_content_type: 게시물의 기본 형식
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: 마크다운
        setting_default_content_type_plain: 일반 텍스트
        setting_favourite_modal: 관심글을 지정할 때 다시 물어보기 (글리치 테마만)
        setting_show_followers_count: 팔로워 수 표시
        setting_skin: 스킨
        setting_system_emoji_font: 에모지에 시스템 기본 폰트 적용하기 (글리치 테마만)
      notification_emails:
        trending_link: 새로 유행중인 링크에 대한 리뷰가 필요할 때
        trending_status: 새로 유행중인 게시물에 대한 리뷰가 필요할 때
        trending_tag: 새로 유행중인 해시태그에 대한 리뷰가 필요할 때
