name: Build container release images
on: push

permissions:
  contents: read
  packages: write

jobs:
  get-current-time:
    name: Get Current Time
    runs-on: ubuntu-latest
    steps:
      - name: Get Current TIme
        id: time
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64,linux/arm64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      flavor: |
        latest = true
      tags: |
        type=pep440,pattern=${{ env.MY_DATE }}
    secrets: inherit
