name: Build container release images
on: push

permissions:
  contents: read
  packages: write

jobs:
  get-current-date:
    name: Get Current Date
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        id: time
        run: echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64,linux/arm64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      flavor: |
        latest = true
    secrets: inherit
